### ISSUE TITLE
How to fix Cavalcade?

### ISSUE THREAD

**Issue by photocurio** [humanmade/Cavalcade#96] opened 2020-04-07 16:19 UTC
I am running a version of Altis+Chassis+Wordpress. There is an issue with the Cavalcade module: it throws errors when I have the dubugger open.  See screenshot. 
![Screen Shot 2020-04-07 at 11 28 10 AM](https://user-images.githubusercontent.com/5224038/78691688-e5a6e800-78c6-11ea-8500-dc62b97eb3cb.png)
I am assuming Cavalcade is a dependency of one of the Altis modules.  How do I fix this and confirm that Cavalcade is doing whatever it is supposed to do?
This is the Altis part of my composer.json file:
```
"require-dev": {
        "altis/core": "dev-master",
        "altis/local-chassis": "dev-master",
        "altis/dev-tools": "dev-master",
        "humanmade/coding-standards": "^0.7.0"
    },
    "autoload-dev": {
        "files": []
    },
    "extra": {
        "installer-paths": {
            "content/plugins/{$name}/": [
                "type:wordpress-plugin"
            ],
            "content/mu-plugins/{$name}": [
                "type:wordpress-muplugin"
            ],
            "content/themes/{$name}/": [
                "type:wordpress-theme"
            ]
        },
        "altis": {
            "modules": {
                "local-chassis": {
                    "hosts": [
                        "fresenius.local"
                    ],
                    "multisite": "Yes",
                    "extensions": [
                        "sequelpro",
                        "xdebug",
                        "memcache",
                        "phpini"
                    ]
                }
            }
        }
    }
```

**Comment by rmccue** [comment] 2020-04-08 11:09
Hi @photocurio!

This error is being thrown by a different process to your web process. `altis/local-chassis` includes the Cavalcade daemon ([Cavalcade Runner](https://github.com/humanmade/Cavalcade-Runner)) which runs as a system service. This expects the project to have Cavalcade (the WordPress plugin) installed, which would create the required database tables for you.

As I understand your setup from talking to the relevant team, you're not using Cavalcade. That's fine, it just means there's an unnecessary service running inside the Chassis VM. That isn't linked to your project, and the error is benign (it just means the service can't launch).

If you want to avoid that error regardless, you can SSH into the machine and stop the service: first `composer chassis shell`, then `sudo service cavalcade stop`.

This isn't generally an issue with Cavalcade though, but rather with Altis Local Chassis (and its use outside of a full Altis setup; `altis/cloud` would usually include Cavalcade). Going to close this issue as it's not a bug, but happy to answer any further questions :)

**Closed by rmccue** 2020-04-08 11:09 UTC

**Comment by photocurio** [comment] 2020-04-09 00:36
OK, thanks Ryan.
